name: JustAdvent
version: '0.0.1'
main: dev.meyba.justAdvent.JustAdvent
api-version: '1.21'
authors: [ Meyba._., Jezevcik20 ]
description: Just an advent plugin.

commands:
  advent:
    description: Opens the advent calendar
    usage: /<command> [open|reload|help]
    aliases: [adventcalendar, ac, advent, calendar]

permissions:
  justadvent.*:
    description: All JustAdvent permissions
    default: op
    children:
      justadvent.use: true
      justadvent.reload: true
  justadvent.use:
    description: Allows opening the advent calendar
    default: true
  justadvent.reload:
    description: Allows reloading the configuration
    default: op
